bigquery_demo:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: diesel-command-384802
      dataset: dbt_demo
      threads: 4
      timeout_seconds: 300
      keyfile: "{{ env_var('BIGQUERY_KEYFILE_PATH', '/tmp/bq-keyfile.json') }}"
    ci:
      type: bigquery
      method: service-account
      project: diesel-command-384802
      dataset: dbt_demo_ci
      threads: 4
      timeout_seconds: 300
      keyfile: "{{ env_var('BIGQUERY_KEYFILE_PATH', '/tmp/bq-keyfile.json') }}"
